### ISSUE TITLE
License should be GPLv2

### ISSUE THREAD

**Issue by LoyVanBeek** [RobotRose/dynamixel_joint_state_publisher#1]
http://redmine.robot-rose.nl/redmine/issues/1277
See http://code.google.com/p/ros-by-example/source/browse/trunk/rbx_vol_1/rbx1_dynamixels/nodes/dynamixel_joint_state_publisher.py?r=60#13

**Comment by OkkeHendriks** [comment]
'or (at your option) any later version.'

Close this?
